"""
HydroGuard-AI — Climatology Store
===================================
Loads pre-computed per-city, per-month weather quantiles from JSON files.
Used by FeaturePipelineV2 to compute climatological context features
(prcp_climo_pct, pressure_climo_z, humidity_climo_pct).

JSON files live at: backend/data/climatology/<city_slug>.json
Generated by: scripts/compute_climatology.py

Falls back to global stats (computed across all cities) when a
city-specific file is missing.
"""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Optional

from app.core.config import DATA_DIR

logger = logging.getLogger(__name__)

CLIMATOLOGY_DIR = DATA_DIR / "climatology"


# ─────────────────────────────────────────────────────────────
#  Data models
# ─────────────────────────────────────────────────────────────

@dataclass
class MonthlyStats:
    q50:   float = 0.0
    q90:   float = 1.0
    q99:   float = 2.0
    mu:    float = 0.0
    sigma: float = 1.0

    @classmethod
    def from_dict(cls, d: dict) -> "MonthlyStats":
        return cls(
            q50=float(d.get("q50", 0.0)),
            q90=float(d.get("q90", 1.0)),
            q99=float(d.get("q99", 2.0)),
            mu =float(d.get("mu",  0.0)),
            sigma=max(float(d.get("sigma", 1.0)), 1e-9),
        )


@dataclass
class CityClimatology:
    city_slug:          str
    computed_from_rows: int
    # month (1-12) → feature_name → MonthlyStats
    monthly: Dict[int, Dict[str, MonthlyStats]] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, d: dict) -> "CityClimatology":
        monthly: Dict[int, Dict[str, MonthlyStats]] = {}
        for month_str, feat_dict in d.get("monthly", {}).items():
            m = int(month_str)
            monthly[m] = {
                feat: MonthlyStats.from_dict(stats)
                for feat, stats in feat_dict.items()
            }
        return cls(
            city_slug          = d.get("city_slug", "unknown"),
            computed_from_rows = d.get("computed_from_rows", 0),
            monthly            = monthly,
        )


# ─────────────────────────────────────────────────────────────
#  Defaults (used when city file or month is missing)
# ─────────────────────────────────────────────────────────────

_FEATURE_DEFAULTS: Dict[str, MonthlyStats] = {
    "prcp":     MonthlyStats(q50=5.0,  q90=40.0,  q99=100.0, mu=10.0,  sigma=15.0),
    "pressure": MonthlyStats(q50=1013.0, q90=1018.0, q99=1022.0, mu=1012.0, sigma=5.0),
    "humidity": MonthlyStats(q50=55.0, q90=82.0,  q99=93.0,  mu=56.0,  sigma=18.0),
    "cloud_cover": MonthlyStats(q50=30.0, q90=85.0, q99=97.0, mu=38.0, sigma=30.0),
    "tmax":     MonthlyStats(q50=28.0, q90=38.0,  q99=43.0,  mu=27.0,  sigma=7.0),
    "tmin":     MonthlyStats(q50=15.0, q90=25.0,  q99=29.0,  mu=14.0,  sigma=6.0),
    "wspd":     MonthlyStats(q50=8.0,  q90=20.0,  q99=35.0,  mu=9.0,   sigma=6.0),
    "dew_point":MonthlyStats(q50=10.0, q90=22.0,  q99=27.0,  mu=11.0,  sigma=7.0),
}


# ─────────────────────────────────────────────────────────────
#  Store
# ─────────────────────────────────────────────────────────────

class ClimatologyStore:
    """
    Lazy-loads climatology JSON files per city on first access.
    Thread-safe for reads (no mutation after load).
    """

    def __init__(self, climatology_dir: Path = CLIMATOLOGY_DIR):
        self._dir: Path = climatology_dir
        self._cache: Dict[str, CityClimatology] = {}

    # ── Public API ──────────────────────────────────────────

    def load(self, city_slug: str) -> CityClimatology:
        """Load (and cache) the climatology for a city. Falls back to defaults."""
        if city_slug not in self._cache:
            self._cache[city_slug] = self._load_or_default(city_slug)
        return self._cache[city_slug]

    def get_stats(
        self,
        city_slug: str,
        month: int,
        feature: str,
    ) -> MonthlyStats:
        """Return MonthlyStats for a city x month x feature triple."""
        clim   = self.load(city_slug)
        m_data = clim.monthly.get(month, {})
        if feature in m_data:
            return m_data[feature]
        # Fall back to default
        return _FEATURE_DEFAULTS.get(feature, MonthlyStats())

    def prcp_climo_pct(self, city_slug: str, month: int, prcp: float) -> float:
        """
        prcp / city x month q90.
        >1.0 means climatologically extreme. Returns 0.0 if prcp is None/negative.
        """
        if prcp is None or prcp < 0:
            return 0.0
        stats = self.get_stats(city_slug, month, "prcp")
        q90 = max(stats.q90, 0.1)    # avoid division by zero in dry months
        return float(prcp / q90)

    def pressure_climo_z(self, city_slug: str, month: int, pressure: float) -> float:
        """
        (pressure - city x month mean) / city x month std.
        Negative z = low pressure (destabilising). Capped at +-5.
        """
        if pressure is None:
            return 0.0
        stats = self.get_stats(city_slug, month, "pressure")
        z = (pressure - stats.mu) / max(stats.sigma, 0.1)
        return float(max(-5.0, min(5.0, z)))

    def humidity_climo_pct(self, city_slug: str, month: int, humidity: float) -> float:
        """
        humidity / city x month q90. Capped at 2.0.
        """
        if humidity is None:
            return 0.0
        stats = self.get_stats(city_slug, month, "humidity")
        q90 = max(stats.q90, 1.0)
        return float(min(humidity / q90, 2.0))

    def reload(self, city_slug: str) -> None:
        """Force reload from disk (e.g. after recompute_climatology)."""
        self._cache.pop(city_slug, None)

    # ── Private helpers ─────────────────────────────────────

    def _load_or_default(self, city_slug: str) -> CityClimatology:
        path = self._dir / f"{city_slug}.json"
        if path.exists():
            try:
                data = json.loads(path.read_text(encoding="utf-8"))
                clim = CityClimatology.from_dict(data)
                logger.debug("Climatology loaded: %s (%d rows)", city_slug, clim.computed_from_rows)
                return clim
            except Exception as exc:
                logger.warning("Failed to load climatology for %s: %s", city_slug, exc)
        else:
            logger.debug("No climatology file for %s — using global defaults", city_slug)
        # Return empty climatology; get_stats falls back to _FEATURE_DEFAULTS
        return CityClimatology(city_slug=city_slug, computed_from_rows=0)


# Module-level singleton
climatology_store = ClimatologyStore()
